[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.4"
  GO_VERSION = "1.24.2"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"

# Redirect rules for admin access
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Ensure admin files are served correctly
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
