backend:
  name: github
  repo: simonejiang7/na-li-portfolio
  branch: main

media_folder: "static/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "content", widget: "markdown"}

      - name: "contact"
        label: "Contact Page"
        file: "content/contact/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "content", widget: "markdown"}

  - name: "legal"
    label: "Legal Pages"
    files:
      - name: "privacy"
        label: "Privacy Policy"
        file: "content/privacy-policy/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}

      - name: "legal_mentions"
        label: "Legal Mentions"
        file: "content/legal-mentions/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}

  - name: "site_settings"
    label: "Site Settings"
    files:
      - name: "banner"
        label: "Banner Settings"
        file: "data/banner.yml"
        fields:
          - {label: "Enable Banner", name: "enable", widget: "boolean", default: false}
          - {label: "Banner Text", name: "text", widget: "string", required: false}
          - {label: "Banner Link", name: "link", widget: "string", required: false}

      - name: "seo"
        label: "SEO Settings"
        file: "data/seo.yml"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Author", name: "author", widget: "string", required: false}
